on:
  pull_request:
   types: [opened, synchronize]
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  check-branch-name:
    name: Check branch name
    runs-on: ubuntu-20.04
    steps:

      - name: Check branch prefix naming
        if: contains(fromJson('["fix/", "feat/", "junk/", "maint/", "doc/", "no-ci/", "testing/", "release/"]'), env.BRANCH_NAME) == false
        run: echo "[ERROR] Branch name ${{ env.BRANCH_NAME }} prefix is not valid." && exit 1

  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}