on:
  pull_request:
   types: [opened, synchronize]
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  check-name:
    name: Check branch name
    runs-on: ubuntu-20.04
    steps:
      - uses: jungwinter/split@master
        id: split
        with:
          msg: ${{ env.BRANCH_NAME }}
          separator: "/"
          maxsplit: -1
      - name: Check branch naming
        if: false == (contains(fromJson('["feat", "fix"]'), ${{ steps.split.outputs._0 }}))
        run: echo "::error::Prefix ${{ steps.split.outputs._0 }} doesn't match possible branch prefixes" && exit 1
        